version: '2.2'
# Tests & Build: source code --> distribution code

# USAGE (from root directory): docker-compose -f <filePath> up <service>
services:
    
    proxy: # used as image, not meant to be run.
        build: # change context to project's root folder.
            context: ../../
            dockerfile: ./setup/container/containerBuild.dockerfile
        image: myuserindocker/redbird-reverseproxy:latest # name of biult image cannot be uppercase.
        ports:
            - 80:80
            - 443:443
        environment:
            DEPLOYMENT: ${DEPLOYMENT:-production}
            EMAIL: ${EMAIL}
            LETSENCRYPT_PORT: ${LETSENCRYPT_PORT}
        volumes:
          - ../../source/server/:/project/application/server/
        working_dir: /project/application/
        # entrypoint: /tmp/shellScript/entrypoint.sh
        # command: bash -c ""
    
    development:
        image: myuserindocker/deployment-environment:latest
        volumes:
            - ../../source/server/:/project/application/server/
        command: bash -c "sleep 100000"
